layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 12
  exclude:
    archived: false
    forks: false
    projects:
     - kiernann.com
     - k5cents.com
     - plaintext
     - personal-website

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
   linkedin: kiernann
   mastodon: @kiernan
   medium: kiernann
  # stackoverflow: your_user_id
  # telegram: your_username
   twitter: kiernxn
  # unsplash: your_username
  # vk: your_username
  # website: http://kiernann.dev
  # youtube: KiernanNicholls

topics:
  - name: R
    web_url: https://github.com/topics/R
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/r/r.png

  - name: Tidyverse
    web_url: https://github.com/topics/tidyverse
    image_url: https://www.tidyverse.org/images/hex-tidyverse.png

  - name: Markdown
    web_url: https://github.com/topics/sass
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/markdown/markdown.png
